import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import pc from "picocolors";
import {
  AGENTS,
  DEFAULT_AGENTS,
  expandHome,
  type AgentId,
} from "./paths.js";
import {
  SKILL_META,
  SKILL_NAMES,
  type InstallOptions,
  type SkillName,
} from "./types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const PKG_ROOT = resolve(__dirname, "..");
export const SKILLS_ROOT = join(PKG_ROOT, "skills");

function copyDir(src: string, dest: string, force: boolean): void {
  if (existsSync(dest)) {
    if (!force) return;
    rmSync(dest, { recursive: true, force: true });
  }
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(src, dest, { recursive: true });
}

export function listBundledSkills(): SkillName[] {
  return SKILL_NAMES.filter((name) =>
    existsSync(join(SKILLS_ROOT, name, "SKILL.md")),
  );
}

export function installSkills(opts: InstallOptions): void {
  const bundled = listBundledSkills();
  const toInstall = opts.skills.length
    ? opts.skills.filter((s) => bundled.includes(s))
    : bundled;

  if (!toInstall.length) {
    console.log(pc.yellow("没有找到可安装的 skill。"));
    return;
  }

  const agentIds = opts.agents.length ? opts.agents : DEFAULT_AGENTS;
  const targets = new Set<string>();

  for (const agentId of agentIds) {
    const agent = AGENTS.find((a) => a.id === agentId);
    if (!agent) continue;
    for (const rel of agent.dirs({ global: opts.global })) {
      const base = expandHome(rel, homedir());
      const abs = opts.global ? base : resolve(opts.cwd, rel);
      for (const skill of toInstall) {
        targets.add(join(abs, skill));
      }
    }
  }

  let installed = 0;
  for (const dest of targets) {
    const skillName = dest.split(/[/\\]/).pop() as SkillName;
    const src = join(SKILLS_ROOT, skillName);
    if (!existsSync(join(src, "SKILL.md"))) continue;
    const existed = existsSync(dest);
    if (existed && !opts.force) {
      console.log(pc.dim(`跳过 ${skillName}（已存在）→ ${dest}`));
      continue;
    }
    copyDir(src, dest, opts.force);
    installed++;
    console.log(
      pc.green(`${existed ? "更新" : "安装"} ${skillName}`) + pc.dim(` → ${dest}`),
    );
  }

  if (opts.agentsMd && !opts.global) {
    writeAgentsMd(opts.cwd, toInstall);
  }

  console.log(pc.dim(`\n完成 ${installed} 处安装。`));
  console.log(pc.dim("分发: npx skills add G12789/ai-ship"));
}

function writeAgentsMd(cwd: string, skills: SkillName[]): void {
  const tplPath = join(PKG_ROOT, "templates", "AGENTS.md.tpl");
  const outPath = resolve(cwd, "AGENTS.md");

  const lines: string[] = [
    "# AGENTS.md",
    "",
    "> Generated by [ai-ship](https://github.com/G12789/ai-ship). Edit freely.",
    "",
    "## AI Ship Skills",
    "",
    "本项目安装了以下 Agent Skills（`SKILL.md` 工作流 + 可执行 scripts）：",
    "",
  ];

  for (const name of skills) {
    const meta = SKILL_META[name];
    lines.push(`- **${name}** — ${meta.title}（${meta.frequency}）`);
  }

  lines.push(
    "",
    "## 手动 CLI（不通过 Agent 时）",
    "",
    "```bash",
    "npx ai-ship ctx          # 打包会话上下文",
    "npx ai-ship eval         # prompt 回归测试",
    "npx ai-ship mcp <name>   # 生成 MCP Server",
    "npx ai-ship check        # 提交前检查",
    "```",
    "",
    "## 验证改动",
    "",
    "改完代码后跑项目自己的 test/lint；改 prompt 后跑 `npx evaldrift run`。",
    "",
  );

  if (existsSync(tplPath)) {
    const extra = readFileSync(tplPath, "utf8").trim();
    if (extra) {
      lines.push("## 项目说明", "", extra, "");
    }
  }

  if (existsSync(outPath)) {
    console.log(pc.yellow("AGENTS.md 已存在，未覆盖。请手动合并 AI Ship 章节。"));
    return;
  }

  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(pc.green("已生成 AGENTS.md"));
}

export function skillScriptPath(skill: SkillName): string | null {
  const candidates = ["run.mjs", "pack.mjs", "check.mjs", "scaffold.mjs"];
  for (const file of candidates) {
    const p = join(SKILLS_ROOT, skill, "scripts", file);
    if (existsSync(p)) return p;
  }
  return null;
}

const SKILLS_WITHOUT_SCRIPT = new Set<SkillName>(["vision-auto"]);

export function validateBundle(): string[] {
  const errors: string[] = [];
  for (const name of SKILL_NAMES) {
    const md = join(SKILLS_ROOT, name, "SKILL.md");
    if (!existsSync(md)) errors.push(`缺少 skills/${name}/SKILL.md`);
    if (!SKILLS_WITHOUT_SCRIPT.has(name) && !skillScriptPath(name)) {
      errors.push(`缺少 skills/${name}/scripts/*.mjs`);
    }
  }
  return errors;
}

export function parseSkillList(raw: string | undefined): SkillName[] {
  if (!raw || raw === "*") return [...SKILL_NAMES];
  return raw.split(",").map((s) => s.trim()) as SkillName[];
}

export function parseAgentList(raw: string | undefined): AgentId[] {
  if (!raw || raw === "all") return AGENTS.map((a) => a.id);
  return raw.split(",").map((s) => s.trim() as AgentId);
}
